version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aia-learning-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=https://aulaai.com.br
      - NEXTAUTH_SECRET=your-secret-key-here
    volumes:
      - ./prisma:/app/prisma
      - ./backups:/app/backups
    networks:
      - aia-network

  # Nginx como proxy reverso (opcional - pode usar o Nginx do host)
  nginx:
    image: nginx:alpine
    container_name: aia-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    depends_on:
      - app
    networks:
      - aia-network

networks:
  aia-network:
    driver: bridge

volumes:
  app-data: 